# Generated by Django 2.2.4 on 2019-08-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_coord', to='main.Coord'),
        ),
    ]
