# Generated by Django 2.2.4 on 2019-11-25 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190822_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Challenge Name')),
                ('average', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coord',
            name='country',
        ),
        migrations.RemoveField(
            model_name='game',
            name='country',
        ),
        migrations.AddField(
            model_name='coord',
            name='reports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='result',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, max_length=25, verbose_name='display name'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coord',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coord_challenge', to='main.Challenge'),
        ),
        migrations.AddField(
            model_name='game',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_challenge', to='main.Challenge'),
        ),
    ]
