# Generated by Django 2.2.4 on 2020-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200117_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='average',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Challenge Name'),
        ),
    ]
